echo "Copying all work DLLs to update folder..."
cd "Dark Basic Pro\Compiler\plugins"
copy "*.dll" ".\..\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\plugins\"

echo "Copying all Compiler EXEs..."
cd ".."
copy "DBPCompiler.exe" ".\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\"
copy "DBPDebugger.exe" ".\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\"
copy "TGCCertificateViewer.exe" ".\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\"
copy "TGCCertificateViewerKEEPACTIVE.exe" ".\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\"
copy "TGCFree.exe" ".\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\"
copy "TGCOnline.exe" ".\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\"
copy "TGCVerifier.exe" ".\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\"

echo "Copying specific user DLLS..."
cd "plugins-user"
copy "DBProMultiplayerPlusDebug.dll" ".\..\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\plugins-user\"
copy "DBProODEDebug.dll" ".\..\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\plugins-user\"
copy "ShaderData.dll" ".\..\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\plugins-user\"

echo "Copying specific licensed DLLS..."
cd ".."
cd "plugins-licensed"
copy "AdvancedTerrain.dll" ".\..\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\plugins-licensed\"
copy "AdvancedTerrainExpansionPack.loc" ".\..\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\plugins-licensed\"
copy "DBProGameFX.dll" ".\..\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\plugins-licensed\"
copy "PhysicsMain_PC_Master.dll" ".\..\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\plugins-licensed\"
copy "PhysicsMainLang_PC.loc" ".\..\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\plugins-licensed\"

echo "Copying effects and lang folders..."
cd ".."
cd "effects"
copy "*.fx" ".\..\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\effects\"
cd ".."
cd "lang"
cd "english"
copy "*.txt" ".\..\..\..\..\..\Dark Basic Pro Shared\UPDATES\U7.5\Main\Compiler\lang\english\"

echo "finished."
